- hosts: "{{ ec2_group_name }}"
  remote_user: "{{ ec2_ssh_username }}"
  become: yes
  gather_facts: no
  vars_files: vars.yml
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest
    - service:
        name: apache2
        state: started
        enabled: yes
