- hosts: "{{ ec2_group_name }}"
  remote_user: "{{ ec2_ssh_username }}"
  become: yes
  gather_facts: no
  vars_files: vars.yml
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest
    - name: Copy index page
      copy:
        src: files/index.html
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: /etc/ssl/private/self.pem
    - name: Generate an OpenSSL CSR
      openssl_csr:
        path: /etc/ssl/certs/self.csr
        privatekey_path: /etc/ssl/private/self.pem
        common_name: "{{ ec2_group_name }}"
    - name: Generate a Self Signed OpenSSL certificate.
      openssl_certificate:
        path: /etc/ssl/certs/self.pem
        privatekey_path: /etc/ssl/private/self.pem
        csr_path: /etc/ssl/certs/self.csr
        provider: selfsigned
    - name: Enable Apache SSL module
      notify: apache2 restart
      apache2_module:
        name: ssl
    - name: Enable Apache Rewrite module
      notify: apache2 restart
      apache2_module:
        name: rewrite
    - name: Copy Apache default conf
      notify: apache2 restart
      copy:
        src: files/000-default.conf
        dest: /etc/apache2/sites-available/
        owner: root
        group: root
        mode: 0644
    - name: Copy Apache default ssl conf
      notify: apache2 restart
      copy:
        src: files/default-ssl.conf
        dest: /etc/apache2/sites-available/
        owner: root
        group: root
        mode: 0644
    - name: Enable Apache default vhost(s)
      notify: apache2 restart
      command: a2ensite *
    - service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: apache2 restart
      service: name=apache2 state=reloaded
